### PR TITLE
Fix leak on panic in `insert_many`.

### LINKED ISSUE #208: Panicking insert_many leaks memory
The `test_insert_many_panic` test leaks memory. Both of these allocations here to do get freed, presumably due to the panicking `insert_many`:

https://github.com/servo/rust-smallvec/blob/3957cd8b36665e8199ac76f7e50c37a23d658a51/lib.rs#L2096-L2101

Found by Miri:
```
note: tracking was triggered
    --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/liballoc/alloc.rs:80:47
     |
80   |     __rust_alloc(layout.size(), layout.align())
     |                                               ^ created allocation with id 129830
     |
     = note: inside `alloc::alloc::alloc` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/liballoc/alloc.rs:80:47
     = note: inside `<alloc::alloc::Global as core::alloc::AllocRef>::alloc` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/liballoc/alloc.rs:174:49
     = note: inside `alloc::alloc::exchange_malloc` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/liballoc/alloc.rs:268:11
     = note: inside `alloc::boxed::Box::<bool>::new` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/liballoc/boxed.rs:174:9
note: inside `tests::test_insert_many_panic` at lib.rs:2100:26
    --> lib.rs:2100:26
     |
2100 |                 dropped: Box::new(false),
     |                          ^^^^^^^^^^^^^^^
note: inside closure at lib.rs:2072:5
    --> lib.rs:2072:5
     |
2072 | /     fn test_insert_many_panic() {
2073 | |         struct PanicOnDoubleDrop {
2074 | |             dropped: Box<bool>,
2075 | |         }
...    |
2107 | |         assert!(result.is_err());
2108 | |     }
     | |_____^

The following memory was leaked:
alloc129816 (Rust heap, size: 1, align: 1) {
    00                                              │ .
}
alloc129830 (Rust heap, size: 1, align: 1) {
    00                                              │ .
}
```

### PR DESCRIPTION
**Pull request by mbrubeck**
Fixes #208 and reverts the workaround added in #209. CC @RalfJung.

### CODE REVIEW

File: lib.rs [hunk 1]
```diff
@@ -898,10 +901,17 @@ impl<A: Array> SmallVec<A> {
                     ptr = self.as_mut_ptr().add(index);
                     cur = ptr.add(num_added);
                     ptr::copy(cur, cur.add(1), old_len - index);
+
+                    guard.ptr = self.as_mut_ptr();
```
Comment (RalfJung) [inline lib.rs:905]: I am actually somewhat surprised that this does not invalidate `ptr`... doesn't `self.as_mut_ptr()` create a mutable reference that invalidates all other pointers? I suppose this function is called via the `DerefMut` impl, so it even creates an intermediate `&mut [Item]` that covers all elements currently marked as initialized.

Comment (mbrubeck) [reply lib.rs:905]: `len` has been set to zero at this point, so `self` currently derefs to an empty slice.

However, MIRI also does not seem to flag use use of `vec.deref().as_mut_ptr()` to create and use aliasing pointers to elements of non-empty Vecs, so maybe this is just a limitation of MIRI.

Comment (RalfJung) [reply lib.rs:905]: `Vec` has a pointer indirection, so `&mut Vec` just demands exclusive access to the fields of that struct. But I thought smallvec stores (some) elements inline, thus `&mut SmallVec` *does* demand exclusive access to those elements.

> self.len() has been set to zero at this point, so self currently derefs to an empty slice.

Well, but `&mut self` is still being passed fully to `deref_mut`, which covers all inline elements.

Also, an empty slice turned into a raw pointer should only be used to access elements of that slice (the pointer "comes from" the slice and this is restricted to the memory the slice covers). Probably there are just so many raw pointers everywhere here that Miri is fine, but that might change once we experiment with tracking raw pointers more precisely.

Even if nothing goes wrong here (I'd need to dig deeper to find out why), maybe it would be better to follow `Vec` and [have raw pointer methods that do not go through slices](https://github.com/rust-lang/rust/pull/61114)?

Comment (mbrubeck) [reply lib.rs:905]: Thanks, that makes sense. I'll try converting this to replace unique borrows with raw-pointer-only methods.

Comment (mbrubeck) [reply lib.rs]: Updated the code to avoid invalidating raw pointers before using them, and shadowed the `as_ptr` and `as_mut_ptr` methods (as in `std::vec::Vec`) to avoid dereferencing to slice while the contents may be invalid.

Comment (RalfJung) [reply lib.rs]: I don't have time to review this in detail right now but avoiding the intermediate slice is certainly an improvement. At some point I'll make Miri's raw ptr checking more strict and then we'll see what happens here and all over the rest of the ecosystem. ;)

**Comment by mbrubeck** [comment]
Rebased and added some more test cases.  r? @SimonSapin or @jdm

**Comment by jdm** [comment]
@bors-servo r+
Thanks for fixing this!
